spring.application.name=demo

spring.datasource.url=jdbc:postgresql://dpg-d6vregh4tr6s73dq0rp0-a.singapore-postgres.render.com:5432/taxi_booking_axnj?sslmode=require
spring.datasource.username=admin
spring.datasource.password=YLBXle4Ts5DrXIfCg6Vy9aX2qStLZ5d6p

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Server Configuration
server.port=8080